{% set version = "0.1.3" %}

package:
  name: hydra-lsp
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/h/hydra-lsp/hydra_lsp-{{ version }}.tar.gz
  sha256: 5ad3b2d636cb25c1e63289814d5c707b287a5229155f59bad2b953065314b440

build:
  entry_points:
    - hydra-lsp = hydra_lsp.__main__:main
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - importlib-metadata >=6.8.0,<7.0.0
    - intervaltree
    - lsprotocol
    - pygls
    - pygtrie
    - python >={{ python_min }}
    - ruamel.yaml >=0.17.40,<0.18.0

test:
  imports:
    - hydra_lsp
  commands:
    - pip check
    - hydra-lsp --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Retsediv/hydra-lsp
  summary: LSP for Hydra config files
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - danielnachun
